image: maven:latest

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:
        - .m2/repository/
        - target/

stages:
    - build
    - test
    - visualize
    - deploy

CompileCheck:
    stage: build
    script:
        - cd diary
        - mvn compile
    retry: 
        max: 2
        when:
            - always

JUnitTests:
    stage: test
    script:
        - cd diary
        - mvn test -DskipUiTests=true
    retry: 
        max: 2
        when:
            - unknown_failure
            - api_failure
            - runner_system_failure
            - script_failure

premerge_jacoco:
    # Jacoco added based on https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
    stage: test
    script:
        - cd diary
        - mvn $MAVEN_CLI_OPTS clean verify -DskipUiTests=true
        - cat testing/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
    artifacts:
        paths:
            - diary/testing/target/site/jacoco-aggregate/
    interruptible: true
    allow_failure: false
    retry:
        max: 1
    only:   
        variables:
            - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

premerge_coberature:
    # Must be in a stage later than premerge_jacoco's stage.
    # The `visualize` stage does not exist by default.
    # Please define it first, or choose an existing stage like `deploy`.
    stage: visualize
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
    script:
        - python /opt/cover2cover.py diary/testing/target/site/jacoco-aggregate/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > diary/testing/target/site/cobertura.xml
    needs: [premerge_jacoco]
    dependencies:
        - premerge_jacoco
    artifacts:
        reports:
            cobertura: diary/testing/target/site/cobertura.xml
    interruptible: true
    retry:
        max: 1
    only:   
        variables:
            - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

jacocoReport:
    # Jacoco added based on https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
    stage: test
    script:
        - cd diary
        - mvn $MAVEN_CLI_OPTS clean verify -DskipUiTests=true
        - cat testing/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
    artifacts:
        paths:
            - diary/testing/target/site/jacoco-aggregate/
    interruptible: true
    allow_failure: false
    only:
        - master
        - develop

coberatureReport:
    # Must be in a stage later than jacocoReport's stage.
    # The `visualize` stage does not exist by default.
    # Please define it first, or choose an existing stage like `deploy`.
    stage: visualize
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
    script:
        # convert report from jacoco to cobertura, using relative project path
        - python /opt/cover2cover.py diary/testing/target/site/jacoco-aggregate/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > diary/testing/target/site/cobertura.xml
    needs: [jacocoReport]
    dependencies:
        - jacocoReport
    artifacts:
        reports:
            cobertura: diary/testing/target/site/cobertura.xml
    interruptible: true
    only:
        - master
        - develop
