image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
  - command: cd diary; mvn package && mvn exec:java; mvn clean install

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
